export type Startup = {
  slug: string;
  name: string;
  website?: string;
  logo?: string;
  description?: string;
  category?: string;
  country?: string;
  lat?: number;
  lng?: number;
  mrr: number;
  revenueLast30Days: number;
  revenueTotal?: number;
  growthRate?: number;
  customers: number;
  activeSubscriptions: number;
  askingPrice?: number;
  onSale: boolean;
  profitMarginLast30Days?: number;
  multiple?: number;
  firstListedForSaleAt?: string;
  xHandle?: string;
  paymentProvider?: string;
  targetAudience?: string;
  foundedDate?: string;
  lastSyncedAt?: number;
  [key: string]: unknown;
};
